meta_product_name: "Boost-it"
meta_title: "Boost-it - Boost your guests' satisfaction"
meta_description: "Share curated lists of local tips to delight your gusts."
meta_image: "cover.png" # should exist in `app/assets/images/`
